Update Pushover Notifications core version check
easydigitaldownloads/pushover-notifications-edd-ext pull request #31
Opened 2021-07-01 19:06 UTC by robincornett

Fixes #30

Proposed changes:
1. Looking at the core plugin information, it looks like the `CKPN_VERSION` constant existed as early as [version 1.9.2 of the core plugin](https://github.com/wppush/pushover-notifications/blame/f10b6e0b3ca594148ac812ea0e3fe017625e481b/pushover-notifications.php#L14), so I added in a check for that constant and used it for `version_compare` to generate the admin notice.
2. Changed the admin notice to just be a notice instead of a settings error.
3. This technically deprecates the `checkCoreVersion` method, or at least bypasses it, but since it's a private method, I did not formally deprecate it. I think we could potentially just remove it from the class entirely.
4. I would also prefer to do an early return in the `__construct` method, instead of the `else`, but did not do that because it's just a personal preference.
5. I also had to remove the check for if Commissions was active, but since the method is hooked into a Commissions hook, it's only going to run if Commissions is active.

2021-07-12 11:40 UTC, ashleyfae requested changes

2021-07-12 11:40 UTC, ashleyfae commented on pushover-notifications-edd-ext.php
> +		$plugin_folder = get_plugins( '/pushover-notifications' );
I think we still need to adjust this a little.

1. From what I can tell, if Pushover Notifications isn't installed, we get no notice and nothing loads. So we should still show something (presumably?) if it's not even installed.
2. This line specifically (`get_plugins()`) triggers a PHP warning if Pushover Notifications is not installed.

With that in mind, maybe we should do this:

- Check again if `CKPN_VERSION` is defined. If it's not, then show a notice about the plugin missing.
- If it is defined, then we can proceed with the out of date message.
- Remove the `get_plugins()` check.

Also feel free to remove the `checkCoreVersion()` method.

2021-07-19 17:57 UTC, LisaCee commented on pushover-notifications-edd-ext.php
> +		if ( ! $pushover_version || version_compare( $pushover_version, '1.9.3', '<' ) ) {
Is this `version_compare` working for you? I tried to force an error by changing it to '3.0' and it didn't work.

2021-07-19 18:15 UTC, robincornett commented on pushover-notifications-edd-ext.php
> +		if ( ! $pushover_version || version_compare( $pushover_version, '1.9.3', '<' ) ) {
If you want to change the version string here to force the notice to show, you'll need to make the same change in line 153 as it's duplicated there. I guess since that method is only called based on the logic here, it could probably be removed from there. But I think that second round of the logic is why it's not showing the error.

2021-07-20 10:26 UTC, ashleyfae commented on pushover-notifications-edd-ext.php
> +		$plugin_folder = get_plugins( '/pushover-notifications' );
Your fix is working, but it makes the message confusing if pushover isn't installed at all.

Can we change the message contents if Pushover isn't installed? Instead of saying "Update it", just make it a generic "This plugin requires Pushover blah blah blah".

2021-07-20 11:17 UTC, ashleyfae commented on pushover-notifications-edd-ext.php
> +		$plugin_folder = get_plugins( '/pushover-notifications' );
Looks good now. :+1:

2021-07-20 11:18 UTC, ashleyfae requested changes
There are various calls to `is_plugin_active()` that are now fatal erroring. I think they can all just be removed now.

2021-07-20 14:27 UTC, ashleyfae approved these changes

2021-07-20 22:22 UTC, LisaCee approved these changes

2021-07-21 09:16 UTC, merged